### ISSUE TITLE
How to start up this cf-mysql-broker

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/cf-mysql-broker#18]
After tests are successful, how to run this cf-mysql-broker?
Does it have an endpoint for its services, and how to find out.

Thanks
Beth Tran

**Comment by menicosia** [comment]
Hi @betht1220,

I think you are having a hard time understanding how this software works. It may be because you are either not familiar with BOSH (which is how this software is deployed), or with how Services work in Cloud Foundry.

To answer your immediate question, the service broker is automatically managed by BOSH, as described in the [README](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/README.md), under the [Deploying](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/README.md#deploying) section.

Second, in terms of interacting with Cloud Foundry deployed applications, you might want to check out the [Services Overview](http://docs.cloudfoundry.org/services/overview.html) and [application binding](http://docs.cloudfoundry.org/devguide/services/application-binding.html) documents. Note that Cloud Foundry is [typically deployed by BOSH](http://docs.cloudfoundry.org/deploying/) as well.

If none of these documents are helpful to you, it'd probably be best if you can post an issue in terms of what you are trying to accomplish. If we have a better understanding of how the docs are not relevant to your effort, we might better be able to help make you successful.

Hope that helps!

**Comment by menicosia** [comment]
Wow, this issue has been open for a super long time. I lost track of it in the backlog.

I'll go ahead and close it now, but of course feel free to re-open if there's anything we can do to help, or open an entirely new issue if you're having some other difficulty.
